// Generated by gencpp from file assignment_srv/assign_srv.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_SRV_MESSAGE_ASSIGN_SRV_H
#define ASSIGNMENT_SRV_MESSAGE_ASSIGN_SRV_H

#include <ros/service_traits.h>


#include <assignment_srv/assign_srvRequest.h>
#include <assignment_srv/assign_srvResponse.h>


namespace assignment_srv
{

struct assign_srv
{

typedef assign_srvRequest Request;
typedef assign_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct assign_srv
} // namespace assignment_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_srv::assign_srv > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::assignment_srv::assign_srv&) { return value(); }
};

template<>
struct DataType< ::assignment_srv::assign_srv > {
  static const char* value()
  {
    return "assignment_srv/assign_srv";
  }

  static const char* value(const ::assignment_srv::assign_srv&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_srv::assign_srvRequest> should match 
// service_traits::MD5Sum< ::assignment_srv::assign_srv > 
template<>
struct MD5Sum< ::assignment_srv::assign_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_srv::assign_srv >::value();
  }
  static const char* value(const ::assignment_srv::assign_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_srv::assign_srvRequest> should match 
// service_traits::DataType< ::assignment_srv::assign_srv > 
template<>
struct DataType< ::assignment_srv::assign_srvRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_srv::assign_srv >::value();
  }
  static const char* value(const ::assignment_srv::assign_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_srv::assign_srvResponse> should match 
// service_traits::MD5Sum< ::assignment_srv::assign_srv > 
template<>
struct MD5Sum< ::assignment_srv::assign_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_srv::assign_srv >::value();
  }
  static const char* value(const ::assignment_srv::assign_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_srv::assign_srvResponse> should match 
// service_traits::DataType< ::assignment_srv::assign_srv > 
template<>
struct DataType< ::assignment_srv::assign_srvResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_srv::assign_srv >::value();
  }
  static const char* value(const ::assignment_srv::assign_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_SRV_MESSAGE_ASSIGN_SRV_H
