// Generated by gencpp from file assignment_srv/assign_srv_msg.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_SRV_MESSAGE_ASSIGN_SRV_MSG_H
#define ASSIGNMENT_SRV_MESSAGE_ASSIGN_SRV_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_srv
{
template <class ContainerAllocator>
struct assign_srv_msg_
{
  typedef assign_srv_msg_<ContainerAllocator> Type;

  assign_srv_msg_()
    : num1(0)
    , num2(0)  {
    }
  assign_srv_msg_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)  {
  (void)_alloc;
    }



   typedef int32_t _num1_type;
  _num1_type num1;

   typedef int32_t _num2_type;
  _num2_type num2;





  typedef boost::shared_ptr< ::assignment_srv::assign_srv_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_srv::assign_srv_msg_<ContainerAllocator> const> ConstPtr;

}; // struct assign_srv_msg_

typedef ::assignment_srv::assign_srv_msg_<std::allocator<void> > assign_srv_msg;

typedef boost::shared_ptr< ::assignment_srv::assign_srv_msg > assign_srv_msgPtr;
typedef boost::shared_ptr< ::assignment_srv::assign_srv_msg const> assign_srv_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_srv::assign_srv_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_srv::assign_srv_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assignment_srv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'assignment_srv': ['/home/luminescence/RSE_FILES/neu_ros/src/assignment_srv/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assignment_srv::assign_srv_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_srv::assign_srv_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_srv::assign_srv_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_srv::assign_srv_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_srv::assign_srv_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_srv::assign_srv_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_srv::assign_srv_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c68f3979e1a90aac7d1c75a1096d1e60";
  }

  static const char* value(const ::assignment_srv::assign_srv_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc68f3979e1a90aacULL;
  static const uint64_t static_value2 = 0x7d1c75a1096d1e60ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_srv::assign_srv_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_srv/assign_srv_msg";
  }

  static const char* value(const ::assignment_srv::assign_srv_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_srv::assign_srv_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 num1\n\
int32 num2\n\
";
  }

  static const char* value(const ::assignment_srv::assign_srv_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_srv::assign_srv_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct assign_srv_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_srv::assign_srv_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_srv::assign_srv_msg_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num1);
    s << indent << "num2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_SRV_MESSAGE_ASSIGN_SRV_MSG_H
